# Generated by Django 6.0.2 on 2026-02-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_due_date_task_reminder_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reminder_date',
        ),
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
